name: first workflow 
on: [push]
jobs:
    run-shell-command:
        runs-on: ubuntu-latest
        steps:
            -   name: string
                run: echo " welcome to github action"
            -   name: multiline script
                run: |
                    node -v
                    npm -v
            -   name: python command
                run: |
                    import python
                    print(platform.processor())
    